### ISSUE TITLE
exception thrown on phpunit test Q4

### ISSUE THREAD

**Issue by ericprud** [lucaswerkmeister/wb2rdf#1]
## inputs
* Wikibase JSON: [Q4.json](https://github.com/wikimedia/mediawiki-extensions-Wikibase/blob/master/repo/tests/phpunit/data/rdf/entities/Q4.json)
* Base URI: http://www.wikidata.org/
* Data URI: http://www.wikidata.org/wiki/Special:EntityData

## result:
```
Notice: Undefined index: id in /data/project/wb2rdf/wb2rdf/index.php on line 235

Fatal error: Uncaught InvalidArgumentException: $serialization must be a string in /data/project/wb2rdf/wb2rdf/vendor/wikibase/data-model/src/Entity/EntityId.php:51
Stack trace:
#0 /data/project/wb2rdf/wb2rdf/vendor/wikibase/data-model/src/Entity/EntityId.php(89): Wikibase\DataModel\Entity\EntityId::assertValidSerialization(NULL)
#1 /data/project/wb2rdf/wb2rdf/vendor/wikibase/data-model/src/Entity/DispatchingEntityIdParser.php(45): Wikibase\DataModel\Entity\EntityId::splitSerialization(NULL)
#2 /data/project/wb2rdf/wb2rdf/index.php(235): Wikibase\DataModel\Entity\DispatchingEntityIdParser->parse(NULL)
#3 /data/project/wb2rdf/wb2rdf/vendor/data-values/serialization/src/Deserializers/DataValueDeserializer.php(122): {closure}(Array)
#4 /data/project/wb2rdf/wb2rdf/vendor/data-values/serialization/src/Deserializers/DataValueDeserializer.php(91): DataValues\Deserializers\DataValueDeserializer->getDeserialization(Array)
#5 /data/project/wb2rdf/wb2rdf/vendor/wikibase/data-model-serialization/src/Deserializers/SnakDeserializer.php in /data/project/wb2rdf/wb2rdf/vendor/wikibase/data-model/src/Entity/DispatchingEntityIdParser.php on line 49
```

Also [Q6.json](https://github.com/wikimedia/mediawiki-extensions-Wikibase/blob/master/repo/tests/phpunit/data/rdf/entities/Q6.json), [Q7.json](https://github.com/wikimedia/mediawiki-extensions-Wikibase/blob/master/repo/tests/phpunit/data/rdf/entities/Q7.json), [Q9.json](https://github.com/wikimedia/mediawiki-extensions-Wikibase/blob/master/repo/tests/phpunit/data/rdf/entities/Q9.json) and  [Q10.json](https://github.com/wikimedia/mediawiki-extensions-Wikibase/blob/master/repo/tests/phpunit/data/rdf/entities/Q10.json)

**Comment by lucaswerkmeister** [comment]
The entity ID values in that JSON are missing the full entity ID:

```json
"value": {
    "entity-type": "item",
    "numeric-id": 42
},
```

Entity ID values you get from `Special:EntityData`, on the other hand, will always contain it:

```json
"value": {
    "entity-type": "item",
    "numeric-id": 42,
    "id": "Q42"
},
```

In general, I think we’re trying to move away from numeric IDs to full IDs, because numeric IDs can’t support federated entities; however, you can currently still edit Wikidata via the API with numeric IDs, so I suppose we should support them here too.

**Comment by ericprud** [comment]
Is the preferred format `"id": "foreign:Q200"` as seen in [the bottom of Q4](https://github.com/wikimedia/mediawiki-extensions-Wikibase/blob/master/repo/tests/phpunit/data/rdf/entities/Q4.json#L266)?
